### ISSUE TITLE
Fail to connect with provided constructors

### ISSUE THREAD

**Issue by brunetto** [weekface/mgorus#11]
Hi, 
thank you for providing this logrus hook. 
I can't connect to my mongo cluster using the provided constructors.
After few attempts I was able to connect to the mongo cluster with this code (coming from few different post found on internet, none of which was enough to work):

```go
dialInfo := &mgo.DialInfo{
	Addrs: []string{
		"cluster-prefix-1.mongodb.net:27017",
		"cluster-prefix-2.mongodb.net:27017",
		"cluster-prefix-3.mongodb.net:27017",
	},
	Timeout:  20 * time.Second,
	Database: "admin",
	Username: "USER",
	Password: "PW",
	DialServer: func(addr *mgo.ServerAddr) (net.Conn, error) {
		conn, err := tls.Dial("tcp", addr.String(), &tls.Config{InsecureSkipVerify: true})
		return conn, err
	},
}

s, err := mgo.DialWithInfo(dialInfo)
if err != nil {
	log.Fatalf(can't connect: %v\n", err)
}
```

I propose the following new constructor with this [PR](https://github.com/weekface/mgorus/pull/10) to let the users be free to connect in whichever way they can: 

```go
func NewHookerFromCollection(collection *mgo.Collection)*hooker{
	return &hooker{c: collection}
}
```

**Comment by weekface** [comment]
Done with https://github.com/weekface/mgorus/pull/10
