### ISSUE TITLE
Mongodb authentication with authenticationDatabase

### ISSUE THREAD

**Issue by im-vincent** [weekface/mgorus#3]
Mongodb authentication with authenticationDatabase

Do not have this option

➜  ~ mongo --help |grep authenticationDatabase
  --authenticationDatabase arg        user source (defaults to dbname)

**Comment by weekface** [comment]
How about this?

`mgorus.NewHookerWithAuth("host:port", "databaseName", "collectionName", "user", "pass")`

**Comment by im-vincent** [comment]
create user

    db.getSiblingDB("admin").createUser(
      {
        "user" : "test1", 
        "pwd" : "test1", 
        roles: [ { "role" : "dbOwner", "db" : "test" } ]
      }
    )
    
    
    db.getSiblingDB("test").createUser(
      {
        "user" : "test2", 
        "pwd" : "test2", 
        roles: [ { "role" : "dbOwner", "db" : "test" } ]
      }
    )



login

test1 Is not specified authenticationDatabase

    [root@6cc674fd1424 ~]# mongo -u test1 -p test1 test
    MongoDB shell version: 3.2.10
    connecting to: test
    2017-02-17T07:35:18.993+0000 E QUERY    [thread1] Error: Authentication failed. :
    DB.prototype._authOrThrow@src/mongo/shell/db.js:1441:20
    @(auth):6:1
    @(auth):1:2

test1 Is specified authenticationDatabase

    [root@6cc674fd1424 ~]# mongo -u test1 -p test1 test --authenticationDatabase admin
    MongoDB shell version: 3.2.10
    connecting to: test
    > db.t.find()
    { "_id" : ObjectId("58a6a7456a83eca86c74c36b") }

test2 Is not specified `authenticationDatabase

    [root@6cc674fd1424 ~]# mongo -u test2 -p test2 test
    MongoDB shell version: 3.2.10
    connecting to: test
    > db.t.find()
    { "_id" : ObjectId("58a6a7456a83eca86c74c36b") }



The difference between

    > db.system.users.find({}).pretty()
    {
    	"_id" : "admin.test1",    //admin
    	"user" : "test1",
    	"db" : "admin",
    	"credentials" : {
    		"SCRAM-SHA-1" : {
    			"iterationCount" : 10000,
    			"salt" : "BiRtPvvBRp/tqp269FwHuw==",
    			"storedKey" : "12DWJXcXcVXE+rgVDFYWqNwyeGo=",
    			"serverKey" : "5ylRZ4yEz7kPwd2AwSWEkXGcaZo="
    		}
    	},
    	"roles" : [
    		{
    			"role" : "dbOwner",
    			"db" : "test"
    		}
    	]
    }
    {
    	"_id" : "test.test2",    //test
    	"user" : "test2",
    	"db" : "test",
    	"credentials" : {
    		"SCRAM-SHA-1" : {
    			"iterationCount" : 10000,
    			"salt" : "fWTVJVSeBGMFZU0pIA1uFg==",
    			"storedKey" : "/lYXe8qqg9boEts7cScqUUH6row=",
    			"serverKey" : "seDbK9m+IqCtpvCP2wCZMhaqYOo="
    		}
    	},
    	"roles" : [
    		{
    			"role" : "dbOwner",
    			"db" : "test"
    		}
    	]
    }

**Comment by im-vincent** [comment]
认证信息放在不同的db下面

**Comment by weekface** [comment]
mgorus use gopkg.in/mgo.v2

but it don't have option with: --authenticationDatabase 

https://github.com/go-mgo/mgo/search?utf8=%E2%9C%93&q=authenticationDatabase

or you can send a  pr.
