### ISSUE TITLE
how to use this hook with logrus levels?

### ISSUE THREAD

**Issue by rpoletaev** [weekface/mgorus#4]
```go
     logHook, err := mgorus.NewHooker(cnf.LogHook.DBHost, cnf.LogHook.DBName, cnf.LogHook.System)
	if err != nil {
		return nil, err
	}

        svc.Logger = log.New()
	svc.Hooks.Add(logHook)
	log.SetLevel(logrus.ErrorLevel)
```
in fact shows all levels logs

**Comment by weekface** [comment]
`shows all levels logs`?

mgorus is just a logrus's hook,
when you use `logrus.Error("logginggggggg")`
mgorus add this message with `Error` level (as a [json object](https://github.com/weekface/mgorus/blob/master/mgorus.go#L40))save to your mongodb.
so it don't print.


the usage is [here](https://github.com/weekface/mgorus#usage)
