### ISSUE TITLE
Dynamic collection

### ISSUE THREAD

**Issue by 0x7061** [weekface/mgorus#9]
Is there any way I can choose the collection dynamically when writing the log?
I need to log to different collections based on if it's a message, execution result etc ...

**Comment by weekface** [comment]
Do you want to configure multiple collections? Or get collection names dynamically from `logrus.Entry`?

**Comment by 0x7061** [comment]
I believe the 1., basically I'm looking for a way to log to different collections depending on the log content.
E.g. `log.WithCollection('errors').WithError(err).Error("foo")`

Or do I have to use multiple logrus instances with different hooks/mongo configs?

**Comment by weekface** [comment]
> use multiple logrus instances with different hooks/mongo configs

maybe a better solution.

**Comment by 0x7061** [comment]
Ok. Thanks.
